Revert "LU-1522 recovery: rework LU-1166 patch in different way"
This reverts commit 4f2c2811b6a69746eb347c05d49ff13fe93e60a6.

The commit 4f2c281 caused mds to LBUG:
LustreError: 10878:0:(mdt_handler.c:5529:mdt_iocontrol()) Aborting recovery for device nbp2-MDT0000^M
LustreError: 11533:0:(lu_object.c:113:lu_object_put()) ASSERTION(cfs_list_empty(&top->loh_lru)) failed^M
LustreError: 11533:0:(lu_object.c:113:lu_object_put()) LBUG^M
Pid: 11533, comm: mdt_rdpg_07^M
^M
Call Trace:^M
 [<ffffffffa056b855>] libcfs_debug_dumpstack+0x55/0x80 [libcfs]^M
 [<ffffffffa056be95>] lbug_with_loc+0x75/0xe0 [libcfs]^M
 [<ffffffffa0576da6>] libcfs_assertion_failed+0x66/0x70 [libcfs]^M